<?php

use Illuminate\Database\Seeder;

class ProductsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('products')->insert([
            [
                'category_id' => 1,
                'name' => 'iPhone X 64GB 2',
                'name_en' => 'iPhone X 64GB 2 EN',
                'code' => 'iphone_x_64',
                'description' => 'Отличный продвинутый телефон с памятью на 64 gb',
                'description_en' => 'Excellent advanced phone with 64 gb memory',
                'image' => 'products/iphone_x.jpg',
                'price' => 71990,
                'hit' => rand(0, 1),
                'new' => rand(0, 1),
                'recommend' => rand(0, 1),
                'count' => rand(0, 10),
            ],
            [
                'category_id' => 1,
                'name' => 'iPhone X 256GB',
                'name_en' => 'iPhone X 256GB EN',
                'code' => 'iphone_x_256',
                'description' => 'Отличный продвинутый телефон с памятью на 256 gb',
                'description_en' => 'Excellent advanced phone with 256 gb memory',
                'image' => 'products/iphone_x_silver.jpg',
                'price' => 89990,
                'hit' => rand(0, 1),
                'new' => rand(0, 1),
                'recommend' => rand(0, 1),
                'count' => rand(0, 10),
            ],
            [
                'category_id' => 1,
                'name' => 'HTC One S',
                'name_en' => 'HTC One S EN',
                'code' => 'htc_one_s',
                'description' => 'Зачем платить за лишнее? Легендарный HTC One S',
                'description_en' => 'Why pay for excess? Legendary HTC One S',
                'image' => 'products/htc_one_s.png',
                'price' => 12490,
                'hit' => rand(0, 1),
                'new' => rand(0, 1),
                'recommend' => rand(0, 1),
                'count' => rand(0, 10),
            ],
            [
                'category_id' => 1,
                'name' => 'iPhone 5SE',
                'name_en' => 'iPhone 5SE EN',
                'code' => 'iphone_5se',
                'description' => 'Отличный классический iPhone',
                'description_en' => 'Great classic iPhone',
                'image' => 'products/iphone_5.jpg',
                'price' => 17221,
                'hit' => rand(0, 1),
                'new' => rand(0, 1),
                'recommend' => rand(0, 1),
                'count' => rand(0, 10),
            ],
            [
                'category_id' => 2,
                'name' => 'Наушники Beats Audio',
                'name_en' => 'Beats Audio earphones',
                'code' => 'beats_audio',
                'description' => 'Отличный звук от Dr. Dre',
                'description_en' => 'Great sound from Dr. Dre',
                'image' => 'products/beats.jpg',
                'price' => 20221,
                'hit' => rand(0, 1),
                'new' => rand(0, 1),
                'recommend' => rand(0, 1),
                'count' => rand(0, 10),
            ],
            [
                'category_id' => 2,
                'name' => 'Камера GoPro',
                'name_en' => 'GoPro camera',
                'code' => 'gopro',
                'description' => 'Снимай самые яркие моменты с помощью этой камеры',
                'description_en' => 'Capture your highlights with this camera',
                'image' => 'products/gopro.jpg',
                'price' => 20221,
                'hit' => rand(0, 1),
                'new' => rand(0, 1),
                'recommend' => rand(0, 1),
                'count' => rand(0, 10),
            ],
            [
                'category_id' => 2,
                'name' => 'Камера Panasonic HC-V770',
                'name_en' => 'Panasonic HC-V770 camera',
                'code' => 'panasonic_hc-v770',
                'description' => 'Для серьёзной видео съемки нужна серьёзная камера. Panasonic HC-V770 для этих целей лучший выбор!',
                'description_en' => 'Serious video shooting requires a serious camera. Panasonic HC-V770 is the best choice for these purposes!',
                'image' => 'products/video_panasonic.jpg',
                'price' => 27900,
                'hit' => rand(0, 1),
                'new' => rand(0, 1),
                'recommend' => rand(0, 1),
                'count' => rand(0, 10),
            ],
            [
                'category_id' => 3,
                'name' => 'Кофемашина DeLongi',
                'name_en' => 'DeLongi coffee machine',
                'code' => 'delongi',
                'description' => 'Хорошее утро начинается с хорошего кофе!',
                'description_en' => 'A good morning starts with good coffee!',
                'image' => 'products/delongi.jpg',
                'price' => 25200,
                'hit' => rand(0, 1),
                'new' => rand(0, 1),
                'recommend' => rand(0, 1),
                'count' => rand(0, 10),
            ],
            [
                'category_id' => 3,
                'name' => 'Холодильник Haier',
                'name_en' => 'Refrigerator Haier',
                'code' => 'haier',
                'description' => 'Для большой семьи большой холодильник!',
                'description_en' => 'A large refrigerator for a large family!',
                'image' => 'products/haier.jpg',
                'price' => 40200,
                'hit' => rand(0, 1),
                'new' => rand(0, 1),
                'recommend' => rand(0, 1),
                'count' => rand(0, 10),
            ],
            [
                'category_id' => 3,
                'name' => 'Блендер Moulinex',
                'name_en' => 'Blender Moulinex',
                'code' => 'moulinex',
                'description' => 'Для самых смелых идей',
                'description_en' => 'For the most daring ideas',
                'image' => 'products/moulinex.jpg',
                'price' => 4200,
                'hit' => rand(0, 1),
                'new' => rand(0, 1),
                'recommend' => rand(0, 1),
                'count' => rand(0, 10),
            ],
            [
                'category_id' => 3,
                'name' => 'Мясорубка Bosch',
                'name_en' => 'Meat grinder Bosch',
                'code' => 'bosch',
                'description' => 'Любите домашние котлеты? Вам определенно стоит посмотреть на эту мясорубку!',
                'description_en' => 'Do you like homemade cutlets? You should definitely take a look at this meat grinder!',
                'image' => 'products/bosch.jpg',
                'price' => 9200,
                'hit' => rand(0, 1),
                'new' => rand(0, 1),
                'recommend' => rand(0, 1),
                'count' => rand(0, 10),
            ],
            [
                'category_id' => 1,
                'name' => 'Samsung Galaxy J6',
                'name_en' => 'Samsung Galaxy J6 EN',
                'code' => 'samsung_j6',
                'description' => 'Современный телефон начального уровня',
                'description_en' => 'Modern entry-level phone',
                'image' => 'products/samsung_j6.jpg',
                'price' => 11980,
                'hit' => rand(0, 1),
                'new' => rand(0, 1),
                'recommend' => rand(0, 1),
                'count' => rand(0, 10),
            ],
        ]);
    }
}
